[package]
name = "zombuddy"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
rcon = { version = "0.6.0", features = ["rt-async-std"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
